config/routes.rb
Rails.application.routes.draw do
  root 'welcomes#index'

  get 'details/:id' => 'details#index', as: :details

  get 'search/list'
end

app/models/hall.rb
class Hall < ActiveRecord::Base
  # TODO きれいじゃない
  scope :include_name, ->(keyword) { where('name LIKE ?', "%#{keyword}%") if keyword.present? }
  scope :include_message, ->(keyword) { where('message LIKE ?', "%#{keyword}%") if keyword.present? }
  scope :include_place, ->(place) { where('address1 = ? or address2 = ? or address3 LIKE ?', place, place, "%#{place}%") if place.present? }

  def address
    address1 + address2 + address3
  end

  def self.search(keyword, place)
    logger.debug 'self.search'
    self.include_name(keyword)
      .include_message(keyword)
      .include_place(place)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/details_controller.rb
class DetailsController < ApplicationController
  def index
    @hall = Hall.find_by_id(detail_params[:id])
  end

  private
  def detail_params
    params.permit(:id)
  end
end

app/controllers/search_controller.rb
class SearchController < ApplicationController
  def list
    @params = search_params
    @halls = Hall.search(@params[:keyword], @params[:place])
  end

  private
  def search_params
    params.require(:search).permit(:keyword, :place)
  end
end

app/controllers/welcomes_controller.rb
class WelcomesController < ApplicationController

  def index
    @halls = Hall.limit(5)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/detail_helper.rb
module DetailHelper
end

app/helpers/search_helper.rb
module SearchHelper
end

app/helpers/welcomes_helper.rb
module WelcomesHelper
end

app/views/details/index.html.erb
<h1><%= @hall.name %></h1>

<ul style="display: flex;">
  <li class="menu_item"><a href="">施設概要</a></li>
  <li class="menu_item"><a href="">写真</a></li>
  <li class="menu_item"><a href="">空室情報</a></li>
  <li class="menu_item"><a href="#" id="show_map" data-address="<%= @hall.address %>">地図</a></li>
</ul>

<div id="overview_container">
  <ul style="display: flex;">
    <li class="hall_photo"><%= image_tag('hall/hall_1.jpg', size: '256x256') %></li>
    <li class="hall_photo"><%= image_tag('hall/hall_2.jpg', size: '256x256') %></li>
  </ul>

  <ul>
    <li>住所：<%= @hall.address %></li>
    <li>連絡先(TEL)：<%= @hall.tel %></li>
    <li>連絡先(email)：<%= mail_to @hall.email %></li>
    <li>広さ：<%= @hall.tatami_num %>畳</li>
    <li>駐車場：10台程度</li>
  </ul>
</div>

<div id="map_container" style="display: none;">
  <div id="map" style="width: 480px; height: 480px;"></div>
</div>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCNorB-sgLibKoKaHFNX-inr3PI0TnFXNA">
</script>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "CloudPublicHall" %></title>
    <%= csrf_meta_tags %>

    <!-- Le HTML5 shim, for IE6-8 support of HTML elements -->
    <!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/3.6.1/html5shiv.js" type="text/javascript"></script>
    <![endif]-->

    <%= stylesheet_link_tag "application", :media => "all" %>

    <%= favicon_link_tag 'apple-touch-icon-144x144-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '144x144' %>
    <%= favicon_link_tag 'apple-touch-icon-114x114-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '114x114' %>
    <%= favicon_link_tag 'apple-touch-icon-72x72-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png', :sizes => '72x72' %>
    <%= favicon_link_tag 'apple-touch-icon-precomposed.png', :rel => 'apple-touch-icon-precomposed', :type => 'image/png' %>
    <%= favicon_link_tag 'favicon.ico', :rel => 'shortcut icon' %>

    <%= javascript_include_tag "application" %>
  </head>
  <body>

    <div class="navbar navbar-default navbar-fixed-top">
      <div class="container">
        <a class="navbar-brand" href="/">クラウド公民館</a>
      </div>
    </div>

    <div class="container" style="margin-top: 60px">
      <div class="row">
        <div class="col-lg-9">
          <%= bootstrap_flash %>
          <%= yield %>
        </div>
      </div>

      <footer>
        <p>&copy; クラウド公民館 2015</p>
      </footer>

    </div>

  </body>
</html>

app/views/partials/_hall_list_item.html.erb
<div class="link_to_detail hall_card" data-url="<%= details_path(hall.id) %>"
  style="display: flex;">
  <div class="hall_detail">
    <h3>
      <span class="hall_num"><%= index %></span>.
      <span class="hall_name"><%= hall.name %></span>
    </h3>
    <div>
      <span><%= hall.address %></span>
    </div>
  </div>
  <div>
    <%= image_tag('hall/hall_1.jpg', size: '128x128') %>
  </div>
</div>

app/views/search/list.html.erb
<div>TOP > <%= @params[:keyword].present? ? @params[:keyword] : '(キーワード指定無し)' %>,<%= @params[:place].present? ? @params[:place] : '(場所指定無し)' %></div>
<h2><%= @halls.count %>件見つかりました</h2>
<div class="col-md-6">
  <% @halls.each_with_index do |hall, index| %>
    <%= render partial: "partials/hall_list_item", locals: {hall: hall, index: index + 1} %>
  <% end %>
</div>

<div id="map" class="col-md-4" style="width: 360px; height: 360px;">
</div>

<script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyCNorB-sgLibKoKaHFNX-inr3PI0TnFXNA&callback=initMap">
</script>
<script>
halls = <%= @halls.to_json.html_safe %>
</script>

app/views/welcomes/index.html.erb
<h1>クラウド公民館</h1>

<div>
  <h2>検索</h2>
  <%= form_tag({controller: 'search', action: 'list'}, method: 'get') do %>
    <%= text_field :search, :keyword, :placeholder => 'キーワード' %>
    <%= text_field :search, :place, :placeholder => '場所' %>
    <%= submit_tag '検索' %>
  <% end %>
</div>
<div class="well" style="float: left; margin-top: 30px;">
  <h2>地図</h2>
<%= image_tag 'map.gif' %>
  <div style="float: right; padding-left: 40px;">
  <table>
    <tr>
      <td>
        <% place_list = ['朝日町', '射水市', '魚津市', "小矢部市","上市町","黒部市","高岡市","立山町","砺波市","富山市","滑川市","南砺市","氷見市","船橋村"] %>
        <% place_list.each do |place| %>
          <%= link_to place, controller: 'search', action: "list", search: {place: place} %>
          <br>
        <% end %>
      </td>
    </tr>

  </table>
  </div>
</div>
<!--<div style="float: left;">-->




<!--</div>-->

<div style="clear:both">
  <h2>市町村別</h2>
</div>
<div>
  <h2>一覧</h2>
  <% @halls.each_with_index do |hall, index| %>
    <%= render partial: "partials/hall_list_item", locals: {hall: hall, index: index + 1} %>
  <% end %>
</div>